sonar.projectKey=herst-connect-v1
sonar.projectName=Herst Connect V1
sonar.host.url=http://100.88.191.49:9010

sonar.sources=src

sonar.exclusions=**/*.test.*,**/*.spec.*,**/node_modules/**,**/.next/**,**/dist/**,**/build/**,**/storybook-static/**,**/coverage/**,**/playwright-report/**,**/test-results/**
sonar.test.inclusions=**/*.test.*,**/*.spec.*

sonar.sourceEncoding=UTF-8
