import { DashCard, DashboardHeader, DashboardShell } from '@/components/admin/dashboard'
import { BentoCard, BentoGrid } from '@/components/admin/grid'
import type { AdminHeroKpi } from '@/components/admin/hero-kpi'
import { Badge } from '@/components/catalyst/badge'
import { requireSession } from '@/lib/auth'
import { BACKEND_ENDPOINTS, pathParamNames, type BackendEndpoint, type EndpointAuth } from '@/lib/backend/endpoints'
import { backendUrl } from '@/lib/env'
import { formatNumber } from '@/lib/format'
import { editorial } from '@/lib/vaults/model'
import {
  BoltIcon,
  BookOpenIcon,
  CpuChipIcon,
  QueueListIcon,
} from '@heroicons/react/16/solid'
import type { Metadata } from 'next'
import { ExplorerRow } from './explorer-row'

export const metadata: Metadata = { title: 'API explorer' }
export const dynamic = 'force-dynamic'

type ExplorerGroup = {
  id: string
  title: string
  description: string
  filter: (endpoint: BackendEndpoint) => boolean
}

const GROUPS: readonly ExplorerGroup[] = [
  {
    id: 'safe-reads',
    title: 'Safe reads',
    description: 'Business GETs and health probes — calling one has no side effect.',
    filter: (e) => e.method === 'GET' && e.category !== 'ai-context',
  },
  {
    id: 'ai-context',
    title: 'AI context',
    description: 'Generated by the backend — never a primary business fact.',
    filter: (e) => e.category === 'ai-context',
  },
  {
    id: 'writes',
    title: 'Writes',
    description:
      'Offers and their steps, decisions, withdrawals, emails, sign-in. Each runs from its own product screen, never from here.',
    filter: (e) => e.method !== 'GET' && e.category !== 'keeper',
  },
  {
    id: 'actions',
    title: 'Keeper actions',
    description: 'Technical requests with side effects — they run from Keeper, each behind an explicit confirmation.',
    filter: (e) => e.category === 'keeper',
  },
]

const AUTH_LEVELS: readonly { auth: EndpointAuth; label: string; detail: string }[] = [
  { auth: 'public', label: 'Public', detail: 'Neither session nor token is required.' },
  { auth: 'session', label: 'Session', detail: 'A signed-in investor or administrator.' },
  { auth: 'admin', label: 'Administrator', detail: 'A session whose backend role is admin.' },
]

function countBy(filter: (e: BackendEndpoint) => boolean): number {
  return BACKEND_ENDPOINTS.filter(filter).length
}

function curlFor(method: string, path: string, auth: string): string {
  const base = backendUrl() ?? '$HEARST_API_URL'
  const lines = [
    `curl -X ${method} '${base}${path}'`,
    `  -H 'Accept: application/json'`,
    `  -H 'X-Request-Id: <uuid>'`,
  ]
  if (auth !== 'public') lines.push(`  -H 'Authorization: Bearer <REDACTED>'`)
  return lines.join(' \\\n')
}

/**
 * API explorer — cockpit shape: compact command bar, then explicit bento rows.
 * BACKEND_ENDPOINTS registry, live probes via ExplorerRow.
 */
export default async function ApiExplorerPage() {
  await requireSession()

  const safeReadsCount = countBy((e) => e.method === 'GET' && e.category !== 'ai-context')
  const aiContextCount = countBy((e) => e.category === 'ai-context')
  const actionsCount = countBy((e) => e.category === 'keeper')

  const kpis: readonly AdminHeroKpi[] = [
    {
      id: 'total',
      title: 'Total endpoints',
      value: editorial(formatNumber(BACKEND_ENDPOINTS.length)),
      icon: QueueListIcon,
    },
    {
      id: 'safe-reads',
      title: 'Safe reads',
      value: editorial(formatNumber(safeReadsCount)),
      icon: BookOpenIcon,
    },
    {
      id: 'actions',
      title: 'Actions',
      value: editorial(formatNumber(actionsCount)),
      icon: BoltIcon,
    },
    {
      id: 'ai-context',
      title: 'AI context',
      value: editorial(formatNumber(aiContextCount)),
      icon: CpuChipIcon,
    },
  ]

  return (
    <DashboardShell>
      <DashboardHeader
        title="API explorer"
        description="Every backend endpoint the console knows — what it does, who may call it, a curl ready to copy."
        kpis={kpis}
      />

      {/* Comment lire la page — trois phrases, plus les niveaux d'accès. */}
      <BentoGrid>
        <BentoCard span={12} bare>
          <DashCard title="How to use it" subtitle="The backend contract as the console declares it — one row per endpoint">
            <div className="flex flex-col gap-3 text-sm text-fg-secondary">
              <p>
                A safe read runs from its row: the response comes back as the backend sent it, with its HTTP status,
                duration and request id. Writes and paths with a <span className="font-mono">:parameter</span> carry no
                button — they run from their own screen, with the value an earlier response gave.
              </p>
              <ul className="flex flex-wrap gap-2">
                {AUTH_LEVELS.map((level) => (
                  <li key={level.auth} className="rounded-full px-3 py-1 text-xs ring-1 ring-[var(--ud-line)]" title={level.detail}>
                    <span className="font-medium text-fg">{level.label}</span>{' '}
                    <span className="text-fg-tertiary">· {formatNumber(countBy((e) => e.auth === level.auth))}</span>
                  </li>
                ))}
              </ul>
            </div>
          </DashCard>
        </BentoCard>
      </BentoGrid>

      {/* Rows C — registry groups: one full-width card per group, the count
          badge on the title row. */}
      {GROUPS.map((group) => {
        const endpoints = BACKEND_ENDPOINTS.filter(group.filter)
        if (endpoints.length === 0) return null

        // Chaque groupe se replie : la page s'ouvre sur quatre lignes, pas sur 11 000 px de routes.
        return (
          <details
            key={group.id}
            className="group rounded-[var(--ud-radius)] bg-[var(--ud-card)] ring-1 ring-[var(--ud-line)]"
          >
            <summary className="flex cursor-pointer list-none items-center gap-3 p-[var(--ud-pad-card)] [&::-webkit-details-marker]:hidden">
              <span className="text-[var(--hearst-green)] transition-transform group-open:rotate-90" aria-hidden="true">
                ▸
              </span>
              <span className="flex min-w-0 flex-1 flex-col">
                <span className="text-[15px] font-medium text-fg">{group.title}</span>
                <span className="text-xs text-fg-tertiary">{group.description}</span>
              </span>
              <Badge color="neutral">{formatNumber(endpoints.length)}</Badge>
            </summary>
            <div className="border-t border-[var(--ud-line)] px-[var(--ud-pad-card)] pb-[var(--ud-pad-card)]">
              {endpoints.map((endpoint) => (
                <ExplorerRow
                  key={endpoint.id}
                  endpoint={endpoint}
                  curl={curlFor(endpoint.method, endpoint.path, endpoint.auth)}
                  pathParams={pathParamNames(endpoint.path)}
                />
              ))}
            </div>
          </details>
        )
      })}
    </DashboardShell>
  )
}
