/**
 * Registry of Hearst Connect backend endpoints — SINGLE SOURCE OF TRUTH.
 *
 * Every surface that talks to the backend (navigation, API Explorer,
 * business pages) reads this registry. No endpoint list is hardcoded
 * elsewhere: a route not listed here does not exist for this frontend.
 *
 * Reference contract: `docs/api.md` from `Hearst-Corporation/hearst-connect-backend`.
 * This file only DESCRIBES the contract; it produces no business data.
 */

export type EndpointCategory = 'probe' | 'business' | 'ai-context' | 'keeper'

export type EndpointAuth =
  /** Public route: neither session nor token. */
  | 'public'
  /** Investor or admin session (signed Bearer token). */
  | 'session'
  /** Session whose backend role is `admin`. */
  | 'admin'

export type BackendEndpoint = {
  /** Stable identifier, used as a UI and test key. */
  id: string
  method: 'GET' | 'POST'
  /** Path as served by the backend. `:index` is a real parameter. */
  path: string
  category: EndpointCategory
  auth: EndpointAuth
  /** Admin page that exposes this endpoint. */
  surface: string
  /**
   * `enveloped: false` → the response is the bare payload (probes, runtime,
   * ai/context, keeper results). Otherwise `{ data, meta }`.
   */
  enveloped: boolean
  /** What the route returns, in one line, for the API Explorer. */
  summary: string
  /**
   * Documented reservation from the backend contract, displayed as-is in
   * the UI. `null` when the route carries none.
   */
  caveat: string | null
}

type EndpointDraft = {
  id: string
  method?: 'GET' | 'POST'
  path: string
  category: EndpointCategory
  auth: EndpointAuth
  surface: string
  enveloped?: boolean
  summary: string
  caveat?: string | null
}

function defineEndpoint(draft: EndpointDraft): BackendEndpoint {
  return {
    id: draft.id,
    method: draft.method ?? 'GET',
    path: draft.path,
    category: draft.category,
    auth: draft.auth,
    surface: draft.surface,
    enveloped: draft.enveloped ?? true,
    summary: draft.summary,
    caveat: draft.caveat ?? null,
  }
}

const CAVEAT_AI = 'Context generated by the backend — never a front-line business fact.'
const CAVEAT_KEEPER_501 = 'Responds 501 with a `KeeperActionResult` (no `code` field): read `reason`.'

export const BACKEND_ENDPOINTS: readonly BackendEndpoint[] = [
  // ── Authentication ─────────────────────────────────────────────────────────
  defineEndpoint({
    id: 'auth-login',
    method: 'POST',
    path: '/api/v1/auth/login',
    category: 'probe',
    auth: 'public',
    surface: '/login',
    enveloped: false,
    summary: 'Email / password authentication — issues the bearer token.',
    caveat: 'Authentication route only — does not produce displayed business data.',
  }),

  // ── Public operational probes ─────────────────────────────────────────────
  defineEndpoint({
    id: 'health',
    path: '/health',
    category: 'probe',
    auth: 'public',
    surface: '/admin/runtime',
    enveloped: false,
    summary: 'Service liveness.',
  }),
  defineEndpoint({
    id: 'ready',
    path: '/ready',
    category: 'probe',
    auth: 'public',
    surface: '/admin/runtime',
    enveloped: false,
    summary: 'Readiness, database included.',
    caveat:
      'On 503, the body is `{ ready: false, db: "unreachable" }` — an orchestrator payload, not a Problem.',
  }),
  defineEndpoint({
    id: 'runtime',
    path: '/api/v1/runtime',
    category: 'probe',
    auth: 'public',
    surface: '/admin/runtime',
    enveloped: false,
    summary: 'Contract mode, chain, indexer lag, version.',
    caveat: 'Non-enveloped response: payload at the top level.',
  }),

  // ── Business data ──────────────────────────────────────────────────────────
  defineEndpoint({
    id: 'dashboard',
    path: '/api/v1/dashboard',
    category: 'business',
    auth: 'session',
    surface: '/admin',
    summary: 'Investor aggregate: identity, position, subscription, runtime.',
    caveat: '`meta.status` is computed worst-field-first: a single degraded field lowers the whole aggregate.',
  }),
  defineEndpoint({
    id: 'profile',
    path: '/api/v1/profile',
    category: 'business',
    auth: 'session',
    surface: '/admin/profile',
    summary: 'Investor profile — one fact, one route.',
  }),
  defineEndpoint({
    id: 'series1-events',
    path: '/api/v1/series1/events',
    category: 'business',
    auth: 'session',
    surface: '/admin/series-1',
    summary: 'Indexed Series 1 events.',
  }),
  defineEndpoint({
    id: 'events-rebalancing',
    path: '/api/v1/events/rebalancing',
    category: 'business',
    auth: 'session',
    surface: '/admin/operations',
    summary: 'Indexed rebalancing events (Rebalance, VaultSwapped, strategy changes).',
    caveat: 'DB-only read model — indexer is the sole writer.',
  }),
  defineEndpoint({
    id: 'clients',
    path: '/api/v1/clients',
    category: 'business',
    auth: 'admin',
    surface: '/admin/clients',
    summary: 'Client directory from the Investor table.',
    caveat: 'Admin role required — enumerates on-book investors only.',
  }),
  defineEndpoint({
    id: 'deployments',
    path: '/api/v1/deployments',
    category: 'business',
    auth: 'admin',
    surface: '/admin/vaults',
    summary: 'Deployment ledger from Position rows.',
    caveat: 'Admin role required — on-book subscriptions, not on-chain deposits.',
  }),
  defineEndpoint({
    id: 'compliance',
    path: '/api/v1/compliance',
    category: 'business',
    auth: 'admin',
    surface: '/admin/conformite',
    summary: 'Compliance review queue from KYC state.',
    caveat: 'Admin role required — investors whose KYC is not approved.',
  }),
  defineEndpoint({
    id: 'vault',
    path: '/api/v1/vault',
    category: 'business',
    auth: 'session',
    surface: '/admin/vaults',
    summary: 'DynaVault state.',
  }),
  defineEndpoint({
    id: 'vault-strategies',
    path: '/api/v1/vault/strategies',
    category: 'business',
    auth: 'session',
    surface: '/admin/vaults',
    summary: 'List of vault strategies.',
    caveat: 'Provides the real indexes for the detail selector — no index is invented on the frontend.',
  }),
  defineEndpoint({
    id: 'strategy-detail',
    path: '/api/v1/strategies/:index',
    category: 'business',
    auth: 'session',
    surface: '/admin/vaults',
    summary: 'Detail of a strategy by index.',
    caveat: '`:index` comes exclusively from the `vault/strategies` response.',
  }),
  defineEndpoint({
    id: 'rwa-vault',
    path: '/api/v1/rwa-vault',
    category: 'business',
    auth: 'session',
    surface: '/admin/vaults',
    summary: 'RWA vault target allocation.',
    caveat: 'TARGET allocation via `strategies()` — never a per-pocket balance.',
  }),
  defineEndpoint({
    id: 'rebalancing-status',
    path: '/api/v1/rebalancing/status',
    category: 'business',
    auth: 'admin',
    surface: '/admin/vaults',
    summary: 'Rebalancing state.',
    caveat: 'Admin role required: a non-admin session receives an HTTP 403 whose body announces 401.',
  }),
  defineEndpoint({
    id: 'mining',
    path: '/api/v1/mining',
    category: 'business',
    auth: 'session',
    surface: '/admin/produit',
    summary: 'Mining aggregate.',
  }),
  defineEndpoint({
    id: 'mining-onchain',
    path: '/api/v1/mining/metrics/onchain',
    category: 'business',
    auth: 'session',
    surface: '/admin/produit',
    summary: 'Mining metrics read on-chain.',
    caveat:
      'Direct on-chain read, distinct from the `mining` aggregate: `/admin/product` compares both and reports any mismatch.',
  }),
  defineEndpoint({
    id: 'mining-electricity',
    path: '/api/v1/mining/electricity',
    category: 'business',
    auth: 'session',
    surface: '/admin/produit',
    summary: 'Mining electricity line item.',
    caveat:
      'Dedicated electricity line read, distinct from `mining.electricity`: `/admin/product` reconciles both.',
  }),
  defineEndpoint({
    id: 'btc',
    path: '/api/v1/btc',
    category: 'business',
    auth: 'session',
    surface: '/admin/produit',
    summary: 'BTC aggregate.',
  }),
  defineEndpoint({
    id: 'product-factsheet',
    path: '/api/v1/product/factsheet',
    category: 'business',
    auth: 'session',
    surface: '/admin/produit',
    summary: 'Product factsheet and terms.',
    caveat:
      '`minimumDepositUsdc` is in whole USDC here, not to be confused with the dashboard\'s `subscription.minimumDeposit`.',
  }),
  defineEndpoint({
    id: 'backtest-historical',
    path: '/api/v1/backtest/historical',
    category: 'business',
    auth: 'session',
    surface: '/admin/produit',
    summary: 'Historical backtest series computed by the backend.',
    caveat: 'Data produced by the backend: the frontend derives no projection from it.',
  }),

  // ── AI context ─────────────────────────────────────────────────────────────
  defineEndpoint({
    id: 'ai-context-dashboard',
    path: '/api/v1/ai/context/dashboard',
    category: 'ai-context',
    auth: 'session',
    surface: '/admin/api-explorer',
    enveloped: false,
    summary: 'Dashboard AI context.',
    caveat: CAVEAT_AI,
  }),
  defineEndpoint({
    id: 'ai-context-btc',
    path: '/api/v1/ai/context/btc',
    category: 'ai-context',
    auth: 'session',
    surface: '/admin/api-explorer',
    enveloped: false,
    summary: 'BTC domain AI context.',
    caveat: CAVEAT_AI,
  }),
  defineEndpoint({
    id: 'ai-context-mining',
    path: '/api/v1/ai/context/mining',
    category: 'ai-context',
    auth: 'session',
    surface: '/admin/api-explorer',
    enveloped: false,
    summary: 'Mining domain AI context.',
    caveat: CAVEAT_AI,
  }),

  // ── Admin ops ──────────────────────────────────────────────────────────────
  defineEndpoint({
    id: 'admin-indexer-trigger',
    method: 'POST',
    path: '/api/v1/admin/indexer/trigger',
    category: 'probe',
    auth: 'admin',
    surface: '/admin/runtime',
    enveloped: false,
    summary: 'Triggers a Series 1 indexer run (admin only).',
    caveat: 'Operational trigger — not a business fact. Not a Keeper write.',
  }),
  defineEndpoint({
    id: 'admin-users',
    method: 'POST',
    path: '/api/v1/admin/users',
    category: 'probe',
    auth: 'admin',
    surface: '/admin/client-simulator/new',
    enveloped: false,
    summary: 'Creates a user account (admin chooses the role).',
    caveat:
      'Strict body `{ email, password, role }` — password is never returned. 201 response `{ user: { id, email, role } }`.',
  }),

  // ── Keeper actions ─────────────────────────────────────────────────────────
  // None of these routes sign a transaction: the service has no on-chain
  // write helper (backend docs/architecture.md).
  defineEndpoint({
    id: 'keeper-mining-report',
    method: 'POST',
    path: '/api/v1/mining/metrics/report',
    category: 'keeper',
    auth: 'admin',
    surface: '/admin/keeper',
    enveloped: false,
    summary: 'Reports mining metrics.',
    caveat: 'Body `{ hashrateTh, btcEarnedSats }`, non-negative bounded integers, `.strict()` validation.',
  }),
  defineEndpoint({
    id: 'keeper-electricity-pay',
    method: 'POST',
    path: '/api/v1/mining/electricity/pay',
    category: 'keeper',
    auth: 'admin',
    surface: '/admin/keeper',
    enveloped: false,
    summary: 'Records an electricity payment.',
    caveat: 'Signs no transaction.',
  }),
  defineEndpoint({
    id: 'keeper-rebalancing-execute',
    method: 'POST',
    path: '/api/v1/rebalancing/execute',
    category: 'keeper',
    auth: 'admin',
    surface: '/admin/keeper',
    enveloped: false,
    summary: 'Requests execution of a rebalancing.',
    caveat: 'Signs no transaction.',
  }),
  defineEndpoint({
    id: 'keeper-rwa-vault',
    method: 'POST',
    path: '/api/v1/rwa-vault',
    category: 'keeper',
    auth: 'admin',
    surface: '/admin/keeper',
    enveloped: false,
    summary: 'RWA vault write.',
    caveat: CAVEAT_KEEPER_501,
  }),
  defineEndpoint({
    id: 'keeper-btc-deposit-initiate',
    method: 'POST',
    path: '/api/v1/btc-deposit/initiate',
    category: 'keeper',
    auth: 'admin',
    surface: '/admin/keeper',
    enveloped: false,
    summary: 'Opens a BTC deposit.',
    caveat: CAVEAT_KEEPER_501,
  }),
  defineEndpoint({
    id: 'keeper-btc-deposit-complete',
    method: 'POST',
    path: '/api/v1/btc-deposit/complete',
    category: 'keeper',
    auth: 'admin',
    surface: '/admin/keeper',
    enveloped: false,
    summary: 'Closes a BTC deposit.',
    caveat: CAVEAT_KEEPER_501,
  }),
] as const

/** Lookup by identifier — throws if the id doesn't exist in the registry. */
export function endpointById(id: string): BackendEndpoint {
  const found = BACKEND_ENDPOINTS.find((endpoint) => endpoint.id === id)
  if (!found) throw new Error(`Endpoint unknown to the registry: "${id}".`)
  return found
}

export function endpointsByCategory(category: EndpointCategory): BackendEndpoint[] {
  return BACKEND_ENDPOINTS.filter((endpoint) => endpoint.category === category)
}

/** Substitutes path parameters. Refuses any missing parameter. */
export function resolvePath(endpoint: BackendEndpoint, params: Record<string, string | number> = {}): string {
  const consumed = new Set<string>()
  const path = endpoint.path.replace(/:(\w+)/g, (_, name: string) => {
    const value = params[name]
    if (value === undefined) {
      throw new Error(`Parameter "${name}" required by ${endpoint.path} and not provided.`)
    }
    consumed.add(name)
    return encodeURIComponent(String(value))
  })

  // BAPI-04: params that are NOT path segments (e.g. `limit`) were silently
  // dropped — `{ params: { limit: 50 } }` never reached the URL, so the backend
  // always returned its default page size. They now become a query string.
  const query = new URLSearchParams()
  for (const [name, value] of Object.entries(params)) {
    if (!consumed.has(name)) query.set(name, String(value))
  }
  const qs = query.toString()
  return qs === '' ? path : `${path}?${qs}`
}
