import { Card } from '@/components/admin/cockpit'
import { AdminCol, AdminGrid } from '@/components/admin/grid'
import { PageHeader } from '@/components/admin/page-header'
import { AdminSection } from '@/components/admin/surfaces'
import { AdminPage, AdminSurfaceTitle } from '@/components/admin/typography'
import { BACKEND_ENDPOINTS, type BackendEndpoint, type EndpointAuth } from '@/lib/backend/endpoints'
import { backendUrl } from '@/lib/env'
import type { Metadata } from 'next'
import { ExplorerRow } from './explorer-row'

export const metadata: Metadata = { title: 'API Explorer' }
export const dynamic = 'force-dynamic'

/**
 * API Explorer — the whole registry, as three lists.
 *
 * This is an inventory screen, and an inventory reads as a list. The rejected
 * version broke the twenty-six routes into four framed panels, one of which
 * held a single row: four boxes to say what one list says better. The
 * grouping that survives is the one a reader acts on — can I call this
 * safely, is this generated context, does this write something — and each
 * group is one card holding its rows, never one card per route.
 *
 * The reading key sits at the top on a declared 8 / 4 row: what a row lets
 * you do on the left, what each authorization level means on the right. Both
 * are read from the registry itself, which is this frontend's single source
 * of truth about the backend surface.
 */

type ExplorerGroup = {
  id: string
  title: string
  description: string
  filter: (endpoint: BackendEndpoint) => boolean
}

const GROUPS: readonly ExplorerGroup[] = [
  {
    id: 'safe-reads',
    title: 'Safe reads',
    description: 'Business GETs and health probes — calling one of these has no side effect.',
    filter: (e) => e.method === 'GET' && e.category !== 'ai-context',
  },
  {
    id: 'ai-context',
    title: 'AI context',
    description: 'Generated by the backend — never a primary business fact.',
    filter: (e) => e.category === 'ai-context',
  },
  {
    id: 'actions',
    title: 'Actions with side effects',
    description:
      'Keeper POSTs, financial and administrative alike. They are listed here for reference and run from Keeper Actions, where each one demands an explicit confirmation.',
    filter: (e) => e.category === 'keeper',
  },
]

/** The three authorization levels the registry declares, in ascending order. */
const AUTH_LEVELS: readonly { auth: EndpointAuth; libelle: string; detail: string }[] = [
  { auth: 'public', libelle: 'Public', detail: 'Neither a session nor a token is needed.' },
  { auth: 'session', libelle: 'Session', detail: 'A signed-in investor or administrator.' },
  { auth: 'admin', libelle: 'Administrator', detail: 'A session whose backend role is admin.' },
]

/**
 * A route whose path carries a `:name` parameter can't be called from the
 * Explorer: the legitimate value comes from a backend response, never from
 * user input. Reading it here avoids offering a button that can never succeed.
 */
function pathParamsOf(path: string): string[] {
  return [...path.matchAll(/:(\w+)/g)].map(([, name]) => name)
}

function curlFor(method: string, path: string, auth: string): string {
  const base = backendUrl() ?? '$HEARST_API_URL'
  const lines = [`curl -X ${method} '${base}${path}'`, `  -H 'Accept: application/json'`, `  -H 'X-Request-Id: <uuid>'`]
  if (auth !== 'public') lines.push(`  -H 'Authorization: Bearer <REDACTED>'`)
  return lines.join(' \\\n')
}

export default function ApiExplorerPage() {
  return (
    <AdminPage>
      <PageHeader
        title="API Explorer"
        description={`Registry of ${BACKEND_ENDPOINTS.length} endpoints. Reads and actions, grouped — no secrets shown.`}
      />

      <AdminGrid>
        <AdminCol span={8}>
          <Card className="p-6">
            <AdminSurfaceTitle as="p">What a row lets you do</AdminSurfaceTitle>
            <p className="mt-3 max-w-prose text-sm/6 text-zinc-600 dark:text-zinc-300">
              A safe read can be called live from its own row. The answer arrives with its HTTP status, its
              duration and its request id, and it is shown as the backend returned it — nothing is cached,
              rounded or rewritten on the way back.
            </p>
            <p className="mt-2 max-w-prose text-sm/6 text-zinc-500 dark:text-zinc-400">
              Two kinds of row carry no button, and say so rather than offering one that could never succeed: a
              POST, which belongs to Keeper Actions and its confirmation step, and a path holding a{' '}
              <span className="font-mono">:parameter</span>, whose legitimate value comes from an earlier
              response rather than from a text field.
            </p>
          </Card>
        </AdminCol>

        <AdminCol span={4} as="aside">
          <Card className="p-5">
            <AdminSurfaceTitle as="p">Authorization</AdminSurfaceTitle>
            <dl className="mt-4 space-y-4">
              {AUTH_LEVELS.map((level) => (
                <div key={level.auth}>
                  <dt className="flex items-baseline justify-between gap-3">
                    <span className="text-sm font-medium text-zinc-950 dark:text-white">{level.libelle}</span>
                    <span className="text-sm tabular-nums text-zinc-500 dark:text-zinc-400">
                      {BACKEND_ENDPOINTS.filter((e) => e.auth === level.auth).length}
                    </span>
                  </dt>
                  <dd className="mt-0.5 text-xs leading-relaxed text-zinc-500 dark:text-zinc-400">
                    {level.detail}
                  </dd>
                </div>
              ))}
            </dl>
          </Card>
        </AdminCol>
      </AdminGrid>

      {GROUPS.map((group) => {
        const endpoints = BACKEND_ENDPOINTS.filter(group.filter)
        if (endpoints.length === 0) return null

        return (
          <AdminSection
            key={group.id}
            title={`${group.title} — ${endpoints.length}`}
            description={group.description}
          >
            {/* One card, one list. The rows already carry their own separator,
                so the card only clips them — it adds no second frame. */}
            <Card className="overflow-hidden">
              {endpoints.map((endpoint) => (
                <ExplorerRow
                  key={endpoint.id}
                  endpoint={endpoint}
                  curl={curlFor(endpoint.method, endpoint.path, endpoint.auth)}
                  pathParams={pathParamsOf(endpoint.path)}
                />
              ))}
            </Card>
          </AdminSection>
        )
      })}
    </AdminPage>
  )
}
