import { PageHeader } from '@/components/admin/page-header'
import { AdminSection, AdminSurface } from '@/components/admin/surfaces'
import { AdminPage } from '@/components/admin/typography'
import { BACKEND_ENDPOINTS, type BackendEndpoint } from '@/lib/backend/endpoints'
import { backendUrl } from '@/lib/env'
import type { Metadata } from 'next'
import { ExplorerRow } from './explorer-row'

export const metadata: Metadata = { title: 'API Explorer' }
export const dynamic = 'force-dynamic'

type ExplorerGroup = {
  id: string
  title: string
  description: string
  filter: (endpoint: BackendEndpoint) => boolean
}

const GROUPS: ExplorerGroup[] = [
  {
    id: 'safe-reads',
    title: 'Safe reads',
    description: 'Business GETs and health probes — no side effects',
    filter: (e) => e.method === 'GET' && e.category !== 'ai-context',
  },
  {
    id: 'ai-context',
    title: 'AI context',
    description: 'Generated by the backend — never a primary business fact',
    filter: (e) => e.category === 'ai-context',
  },
  {
    id: 'financial-actions',
    title: 'Financial actions',
    description: 'Keeper POSTs with operational impact — run them from Keeper',
    filter: (e) =>
      e.category === 'keeper' &&
      ['keeper-mining-report', 'keeper-electricity-pay', 'keeper-rebalancing-execute', 'keeper-btc-deposit-initiate', 'keeper-btc-deposit-complete'].includes(e.id),
  },
  {
    id: 'admin-actions',
    title: 'Administrative actions',
    description: 'Administrative keeper POST — explicit confirmation required',
    filter: (e) => e.category === 'keeper' && e.id === 'keeper-rwa-vault',
  },
]

/**
 * A route whose path carries a `:name` parameter can't be called from the
 * Explorer: the legitimate value comes from a backend response, never from
 * user input. Reading it here avoids offering a button that can never succeed.
 */
function pathParamsOf(path: string): string[] {
  return [...path.matchAll(/:(\w+)/g)].map(([, name]) => name)
}

function curlFor(method: string, path: string, auth: string): string {
  const base = backendUrl() ?? '$HEARST_API_URL'
  const lines = [`curl -X ${method} '${base}${path}'`, `  -H 'Accept: application/json'`, `  -H 'X-Request-Id: <uuid>'`]
  if (auth !== 'public') lines.push(`  -H 'Authorization: Bearer <REDACTED>'`)
  return lines.join(' \\\n')
}

export default function ApiExplorerPage() {
  return (
    <AdminPage>
      <PageHeader
        title="API Explorer"
        description={`Registry of ${BACKEND_ENDPOINTS.length} endpoints. Reads and actions, grouped — no secrets shown.`}
      />

      {GROUPS.map((group) => {
        const endpoints = BACKEND_ENDPOINTS.filter(group.filter)
        if (endpoints.length === 0) return null

        return (
          <AdminSection key={group.id} title={group.title} description={group.description}>
            <AdminSurface>
              {endpoints.map((endpoint) => (
                <ExplorerRow
                  key={endpoint.id}
                  endpoint={endpoint}
                  curl={curlFor(endpoint.method, endpoint.path, endpoint.auth)}
                  pathParams={pathParamsOf(endpoint.path)}
                />
              ))}
            </AdminSurface>
          </AdminSection>
        )
      })}
    </AdminPage>
  )
}
