import { AdminPageHeader, type AdminHeroKpi } from '@/components/admin/page-header'
import { surfaceInset } from '@/components/admin/surface'
import { Badge } from '@/components/catalyst/badge'
import clsx from 'clsx'
import { TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/catalyst/table'
import { Text } from '@/components/catalyst/text'
import { ChartFrame, HearstDonutChart, type DonutSlice } from '@/components/charts'
import { DataTableShell, SectionCard, tableCol } from '@/components/compositions'
import { requireSession } from '@/lib/auth'
import { BACKEND_ENDPOINTS, type BackendEndpoint, type EndpointAuth } from '@/lib/backend/endpoints'
import { backendUrl } from '@/lib/env'
import { formatNumber } from '@/lib/format'
import { editorial } from '@/lib/vaults/model'
import {
  BoltIcon,
  BookOpenIcon,
  CpuChipIcon,
  QueueListIcon,
} from '@heroicons/react/16/solid'
import type { Metadata } from 'next'
import { ExplorerRow } from './explorer-row'

export const metadata: Metadata = { title: 'API explorer' }
export const dynamic = 'force-dynamic'

type ExplorerGroup = {
  id: string
  title: string
  description: string
  filter: (endpoint: BackendEndpoint) => boolean
}

const GROUPS: readonly ExplorerGroup[] = [
  {
    id: 'safe-reads',
    title: 'Safe reads',
    description: 'Business GETs and health probes — calling one has no side effect.',
    filter: (e) => e.method === 'GET' && e.category !== 'ai-context',
  },
  {
    id: 'ai-context',
    title: 'AI context',
    description: 'Generated by the backend — never a primary business fact.',
    filter: (e) => e.category === 'ai-context',
  },
  {
    id: 'actions',
    title: 'Side-effect actions',
    description:
      'Keeper POSTs, financial and administrative. Listed here for reference; they run from Keeper Actions, each requiring explicit confirmation.',
    filter: (e) => e.category === 'keeper',
  },
]

const AUTH_LEVELS: readonly { auth: EndpointAuth; label: string; detail: string }[] = [
  { auth: 'public', label: 'Public', detail: 'Neither session nor token is required.' },
  { auth: 'session', label: 'Session', detail: 'A signed-in investor or administrator.' },
  { auth: 'admin', label: 'Administrator', detail: 'A session whose backend role is admin.' },
]

// Registry breakdown by category: every endpoint genuinely carries this field
// (grouping a per-row datum, not an invented counter), and the total is real
// (= number of endpoints in the registry).
const CATEGORY_LABELS: Record<BackendEndpoint['category'], string> = {
  probe: 'Probes',
  business: 'Business',
  'ai-context': 'AI context',
  keeper: 'Actions Keeper',
}

function pathParamsOf(path: string): string[] {
  return [...path.matchAll(/:(\w+)/g)].map(([, name]) => name)
}

function curlFor(method: string, path: string, auth: string): string {
  const base = backendUrl() ?? '$HEARST_API_URL'
  const lines = [
    `curl -X ${method} '${base}${path}'`,
    `  -H 'Accept: application/json'`,
    `  -H 'X-Request-Id: <uuid>'`,
  ]
  if (auth !== 'public') lines.push(`  -H 'Authorization: Bearer <REDACTED>'`)
  return lines.join(' \\\n')
}

function countBy(filter: (e: BackendEndpoint) => boolean): number {
  return BACKEND_ENDPOINTS.filter(filter).length
}

/**
 * API explorer — composition blocks around the client rows.
 * BACKEND_ENDPOINTS registry, live probes via ExplorerRow.
 */
export default async function ApiExplorerPage() {
  await requireSession()

  const safeReadsCount = countBy((e) => e.method === 'GET' && e.category !== 'ai-context')
  const aiContextCount = countBy((e) => e.category === 'ai-context')
  const actionsCount = countBy((e) => e.category === 'keeper')

  // Parts of a whole: endpoints grouped by their real category.
  const byCategory = new Map<BackendEndpoint['category'], number>()
  for (const endpoint of BACKEND_ENDPOINTS) {
    const seen = byCategory.get(endpoint.category)
    byCategory.set(endpoint.category, seen === undefined ? 1 : seen + 1)
  }
  const categorySlices: readonly DonutSlice[] = [...byCategory.entries()]
    .map(([category, value]) => ({ label: CATEGORY_LABELS[category], value }))
    .sort((a, b) => b.value - a.value)

  const kpis: readonly AdminHeroKpi[] = [
    {
      id: 'total',
      title: 'Total endpoints',
      value: editorial(formatNumber(BACKEND_ENDPOINTS.length)),
      icon: QueueListIcon,
    },
    {
      id: 'safe-reads',
      title: 'Safe reads',
      value: editorial(formatNumber(safeReadsCount)),
      icon: BookOpenIcon,
    },
    {
      id: 'actions',
      title: 'Actions',
      value: editorial(formatNumber(actionsCount)),
      icon: BoltIcon,
    },
    {
      id: 'ai-context',
      title: 'AI context',
      value: editorial(formatNumber(aiContextCount)),
      icon: CpuChipIcon,
    },
  ]

  return (
    <div className="space-y-8">
      <AdminPageHeader
        title="API explorer"
        description="BACKEND_ENDPOINTS registry — safe reads, actions, and AI context."
        kpis={kpis}
      />

      <ChartFrame
        question="How is the registry split by action type?"
        unit="number of endpoints, by category"
        state={{ type: 'plotted' }}
      >
        <HearstDonutChart slices={categorySlices} unit="endpoints" />
      </ChartFrame>

      <SectionCard title="What a row lets you do" tone="plain">
        <Text>
          A safe read can be called directly from its row. The response arrives with its HTTP status,
          its duration and request id, and it is shown exactly as the backend returned it — nothing is
          cached, rounded, or rewritten on return.
        </Text>
        <Text className="mt-4">
          Two row types carry no button, and say so rather than offering one that could never
          succeed: a POST, which belongs to Keeper Actions and its confirmation step, and a path containing a{' '}
          <span className="font-mono">:parameter</span>, whose legitimate value comes from an earlier response
          rather than a text field.
        </Text>
      </SectionCard>

      <DataTableShell
        title="Authorization"
        description="Registry access levels, with the endpoint count at each."
      >
        <TableHead>
          <TableRow>
            <TableHeader className={tableCol.status}>Level</TableHeader>
            <TableHeader className={tableCol.numeric}>Endpoints</TableHeader>
            <TableHeader className={tableCol.primary}>What it requires</TableHeader>
          </TableRow>
        </TableHead>
        <TableBody>
          {AUTH_LEVELS.map((level) => (
            <TableRow key={level.auth}>
              <TableCell className={`${tableCol.status} font-medium`}>{level.label}</TableCell>
              <TableCell className={tableCol.numeric}>
                {formatNumber(countBy((e) => e.auth === level.auth))}
              </TableCell>
              <TableCell className={tableCol.primary}>{level.detail}</TableCell>
            </TableRow>
          ))}
        </TableBody>
      </DataTableShell>

      {GROUPS.map((group) => {
        const endpoints = BACKEND_ENDPOINTS.filter(group.filter)
        if (endpoints.length === 0) return null

        return (
          <SectionCard
            key={group.id}
            title={group.title}
            hint={group.description}
            actions={<Badge color="neutral">{formatNumber(endpoints.length)}</Badge>}
          >
            <div className="overflow-hidden">
              {endpoints.map((endpoint) => (
                <ExplorerRow
                  key={endpoint.id}
                  endpoint={endpoint}
                  curl={curlFor(endpoint.method, endpoint.path, endpoint.auth)}
                  pathParams={pathParamsOf(endpoint.path)}
                />
              ))}
            </div>
          </SectionCard>
        )
      })}

      <SectionCard title="Path parameters" tone="plain">
        <Text>
          Rows with <span className="font-mono">:param</span> are documented but not directly callable —
          the legitimate value comes from an earlier backend response.
        </Text>
      </SectionCard>
    </div>
  )
}
